"""
Core data models for the Nifty Options Spike Detector.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class Bar:
    """A single OHLCV candlestick bar."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int = 0

    def __repr__(self) -> str:
        return (
            f"Bar({self.timestamp.strftime('%H:%M:%S')} "
            f"O={self.open:.2f} H={self.high:.2f} "
            f"L={self.low:.2f} C={self.close:.2f})"
        )


@dataclass
class Tick:
    """A single price tick received from the feed."""
    timestamp: datetime
    security_id: str
    ltp: float           # Last Traded Price
    volume: int = 0


@dataclass
class Indicators:
    """Computed indicator values for a single instrument at a moment in time."""
    rsi: float = 50.0           # RSI (14)
    rsi_ema: float = 50.0       # EMA(50) applied to RSI series
    macd_line: float = 0.0      # MACD line  (fast EMA - slow EMA)
    macd_signal: float = 0.0    # Signal line (EMA of MACD)
    macd_hist: float = 0.0      # Histogram   (MACD - signal)
    # Lookback % moves: {10: 1.2, 20: 3.4, ..., 150: 8.5}
    lookback_pct: dict = field(default_factory=dict)
    # Delta between consecutive lookbacks (shows WHERE acceleration occurred)
    lookback_delta: dict = field(default_factory=dict)
    # Spike ratio: current 10b move / median 10b move over last 100 bars
    # e.g. 4.2 = current move is 4.2× the typical baseline move
    spike_ratio: float | None = None


@dataclass
class OptionInfo:
    """Static metadata about a tracked option."""
    security_id: str
    symbol: str            # e.g. "NIFTY24JAN22150CE"
    strike: int
    option_type: str       # "CE" or "PE"
    expiry: str            # "YYYY-MM-DD"
    label: str             # Human-readable label e.g. "ATM CE"
    underlying: str = ""   # Underlying symbol e.g. "NIFTY", "RELIANCE"


class SignalStatus:
    SPIKE     = "SPIKE"    # Spike detected — watching conditions
    WATCH     = "WATCH"    # RSI + MACD conditions met — wait for breakout
    ENTRY     = "ENTRY"    # Breakout confirmed — entry signal
    EXPIRED   = "EXPIRED"  # Signal expired or conditions broken


@dataclass
class Signal:
    """A trading signal generated by the spike detector."""
    timestamp: datetime
    label: str             # e.g. "ATM CE"
    symbol: str
    strike: int
    option_type: str       # "CE" or "PE"
    direction: str         # "UP" or "DOWN"
    timeframe: str         # "5s", "15s", "1m"
    spike_pct: float       # Magnitude of spike (% in 10-bar window)
    spike_window: int      # Lookback period where spike occurred (bars ago)
    rsi: float
    macd_hist: float
    status: str            # SignalStatus constant
    message: str = ""
    underlying: str = ""   # Underlying symbol e.g. "NIFTY", "RELIANCE"

    def __repr__(self) -> str:
        return (
            f"[{self.timestamp.strftime('%H:%M:%S')}] {self.label} {self.direction} "
            f"spike={self.spike_pct:.1f}% RSI={self.rsi:.1f} "
            f"MACD={'↑' if self.macd_hist > 0 else '↓'} [{self.status}]"
        )


@dataclass
class InstrumentState:
    """Complete runtime state for a single tracked instrument."""
    info: OptionInfo
    ltp: float = 0.0
    prev_ltp: float = 0.0
    # Per-timeframe bar builders (keyed by timeframe string "5s", "15s", "1m")
    # Populated externally by the BarBuilder
    bars: dict = field(default_factory=dict)          # tf -> deque[Bar]
    indicators: dict = field(default_factory=dict)    # tf -> Indicators
    last_update: Optional[datetime] = None
    active_signals: list = field(default_factory=list)

    @property
    def ltp_change_pct(self) -> float:
        if self.prev_ltp > 0:
            return (self.ltp - self.prev_ltp) / self.prev_ltp * 100
        return 0.0
